spring.datasource.url=jdbc:postgresql://localhost:5432/epic-auth-service
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.access-ttl-ms=${JWT_ACCESS_TTL}
jwt.refresh-ttl-ms=${JWT_REFRESH_TTL}

server.port=8083