spring.datasource.url=jdbc:postgresql://epic-auth-postgres:5432/epic-auth-service
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.access-ttl-ms=${JWT_ACCESS_TTL}
jwt.refresh-ttl-ms=${JWT_REFRESH_TTL}

user.service.url=${USER_SERVICE_URL}

app.internal-key=${INTERNAL_API_KEY}